### PR TITLE
Refactor `backends`: migrating `pytorch` and creating `jax`

### PR DESCRIPTION
**Pull request by MatteoRobbiati**

### CODE REVIEW

**Comment by alecandido** [comment]
Just a guess but... I believe you did not receive any feedback on this PR, because you didn't ask anyone :P

Btw, this is targeting https://github.com/qiboteam/qiboml/tree/expectation that has not even a PR...
Since `qiboml` is experimental anyhow, to reduce the complexity of open PRs I'd just merge `expectation` into `main`, and then `backends` into `main` as well. We could keep improving them in further PRs.

**Comment by MatteoRobbiati** [comment]
> Just a guess but... I believe you did not receive any feedback on this PR, because you didn't ask anyone :P

Ups :)

> Btw, this is targeting https://github.com/qiboteam/qiboml/tree/expectation that has not even a PR... Since `qiboml` is experimental anyhow, to reduce the complexity of open PRs I'd just merge `expectation` into `main`, and then `backends` into `main` as well. We could keep improving their content in further PRs.

I changed the targeted branch into main since there are no conflicts anyway.

**Comment by alecandido** [comment]
> I changed the targeted branch into main since there are no conflicts anyway.

Then you can just merge :)

(but please, merge also `expectation`, since the other PRs will work on top of that)

**Comment by alecandido** [comment]
@scarrazza is it possible to enable branch autodeletion?

image

In this way the PRs will be retargeted automatically (this was based on #9, and simply not updated after that one got merged).

**Comment by scarrazza** [comment]
@alecandido, done together with branch protection (main).

**Pull request merged**
