### PR TITLE
Move Pytorch backend

### PR DESCRIPTION
**Pull request by Simone-Bordoni**
Move pytorch backend from qibo to qiboml

### CODE REVIEW

**Comment by Simone-Bordoni** [comment]
We should wait for the new release of qibo in order to merge

**Comment by MatteoRobbiati** [comment]
> We should wait for the new release of qibo in order to merge

Do you think now we can update this and merge @Simone-Bordoni? :)

**Comment by MatteoRobbiati** [comment]
I think now the tests should pass. The backend migrated here is updated with Qibo and a couple of errors have been fixed. Have a look whenever you can @BrunoLiegiBastonLiegi and imho we can merge it.

**Comment by BrunoLiegiBastonLiegi** [comment]
Honestly, I am not sure whether it is worth rushing this by friday. As I see it, there are still two relevant matters open:
- what to do with the tests? Do we leave them in `qibo`, thus creating the same ongoing problems we have with `qibojit` as well, or do we try to solve this once and for all, maybe splitting the tests in the different repos as we were discussing earlier in the meeting?
- The `PyTorchBackend` is not really working for what it's more important (the gradients) qiboteam/qibo#1450, thus we would be moving something buggy anyway

**Comment by MatteoRobbiati** [comment]
> Honestly, I am not sure whether it is worth rushing this by friday. As I see it, there are still two relevant matters open:
> 
> * what to do with the tests? Do we leave them in `qibo`, thus creating the same ongoing problems we have with `qibojit` as well, or do we try to solve this once and for all, maybe splitting the tests in the different repos as we were discussing earlier in the meeting?
> * The `PyTorchBackend` is not really working for what it's more important (the gradients) [Fix pytorch gradients qibo#1450](https://github.com/qiboteam/qibo/pull/1450), thus we would be moving something buggy anyway

I am fine in re-discussing the testing strategy and so post-poning this to next releases. Both your comments are correct and I agree. Anyway, it is useful if we merge this here, no? (without the need of rushing for the migration)

**Comment by BrunoLiegiBastonLiegi** [comment]
Yes we can, I mean `qiboml` is quite a work in progress in any case right now and even the main is not really tested, but I am not sure what this buys us. We will need to open a new PR for the `PyTorchBackend` in any case as soon the gradients problem gets fixed.

**Comment by MatteoRobbiati** [comment]
> Yes we can, I mean `qiboml` is quite a work in progress in any case right now and even the main is not really tested, but I am not sure what this buys us. We will need to open a new PR for the `PyTorchBackend` in any case as soon the gradients problem gets fixed.

Ok, fine. We can keep this open until that moment.

**Pull request closed without merging**
